version: '3'
services:
  app:
    user: root
    container_name: pyspark-app
    build:
      context: .
    image: pyspark
    working_dir: /app
    volumes:
      - .:/app
      - ./datalake:/datalake

  mongo:
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass4mongo

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass4mongo
